### ISSUE TITLE
ライセンス明記のお願い

### ISSUE THREAD

**Issue by nakamura196** [kawabata/kanbun-javascript#2]
本ライブラリを利用させていただきたいので、ライセンスを明記していただけないでしょうか。

**Comment by kawabata** [comment]
関心をお持ちいただき、ありがとうございます。
ちなみに、どのようなライセンスが都合が良いか、参考にお聞かせいただければ幸いです。
（現状では MIT/LGPLのどちらかを考えています。）

**Comment by nakamura196** [comment]
ライセンスの明記について、前向きなご対応をいただきありがとうございます。
この度は開発してくださったライブラリを改変する予定はありませんので、MIT/LGPLどちらのライセンスでも構いません。
どうぞよろしくお願いいたします。

**Comment by kawabata** [comment]
MITLicenseを追記しました。
